In [1]:
import numpy as np

### Practice Problem 1:

In [12]:
#Create a 4  4×4 random matrix and check if it is symmetric.

random_matrix = np.random.randint(1,10,(4,4))
transpose_random = random_matrix.T

#Check symmetry
is_symmetric_random = (random_matrix == transpose_random).all()
print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric? ", is_symmetric_random)

Random Matrix:
 [[3 8 6 8]
 [4 1 9 6]
 [7 7 5 9]
 [1 2 9 1]]

Is the random matrix symmetric?  False


### Practice Problem 2:

In [47]:
#Find the trace of a 5×5 identity matrix.

A = np.array([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]])

def is_identity(A):
    # Get the size of the matrix
    size = A.shape[0]
     
    # Create the identity matrix of the same size
    identity = np.eye(size)
     
    # Check if the matrix is equal to the identity matrix using numpy.allclose
    return np.allclose(A, identity)
 
#Calculate the trace of matrix A
trace_A = np.trace(A)
print("\nTrace of Matrix A:", trace_A)


Trace of Matrix A: 5


### Practice Problem 3:

In [72]:
#Compute the determinant of the following 3×3 matrix using NumPy:
D = np.array([[1,2,3],[0,4,5],[1,0,6]])

#Determinant using NumPy
det_D = np.linalg.det(D)
print("\nDeterminant of Matrix D:", round(det_D))

#Manual computation
#compute = (D[0,0]*((D[1,1]*D[2,2])-(D[1,2]*D[2,1]))) - (D[0,1] * ((D[1,0]*D[2,2])-(D[1,2]*D[2,0]))) + (D[0,2] * ((D[1,0]*D[2,1])-(D[1,1]*D[2,0])))


Determinant of Matrix D: 22


### Practice Problem 4:

In [98]:
#Write code to generate a random 3×33 \times 33×3 matrix representing pixel intensities and find its transpose and determinant.
# Generate a random 3x3 matrix with values representing pixel intensities (0 to 255)
matrix_A = np.random.randint(0, 256, size=(3, 33))
matrix_B = np.random.randint(0, 256, size=(33,3))

result = (matrix_A@matrix_B)

# Calculate the transpose of the matrix
transpose_matrix = np.transpose(result)

# Calculate the determinant of the matrix
determinant = np.linalg.det(result)

print("\nTranspose of the Matrix:\n", transpose_matrix)
print("\nDeterminant of the Matrix:", round(determinant))


Transpose of the Matrix:
 [[574483 520157 538782]
 [639803 570919 600669]
 [484293 412630 513965]]

Determinant of the Matrix: -278462559568366


### Practice Problem 5:

In [104]:
#Symmetric matrices often appear in machine learning algorithms (e.g., covariance matrices). Create a symmetric 3×3 matrix and verify its properties.

A = np.random.randint(0, 10, size=(3, 3))

# Create a symmetric matrix
symmetric_matrix = (A + A.T) // 2 

# Verify symmetry (matrix equals its transpose)
is_symmetric = np.allclose(symmetric_matrix, symmetric_matrix.T)

# Calculate properties of the symmetric matrix
eigenvalues, eigenvectors = np.linalg.eig(symmetric_matrix)  # Eigenvalues and eigenvectors

print("Random Matrix:\n", A)
print("\nSymmetric Matrix:\n", symmetric_matrix)
print("\nIs the matrix symmetric?", is_symmetric)
print("\nEigenvalues of the Symmetric Matrix:\n", eigenvalues)
print("\nEigenvectors of the Symmetric Matrix:\n", eigenvectors)

Random Matrix:
 [[2 9 5]
 [1 2 0]
 [9 5 5]]

Symmetric Matrix:
 [[2 5 7]
 [5 2 2]
 [7 2 5]]

Is the matrix symmetric? True

Eigenvalues of the Symmetric Matrix:
 [12.78843215 -4.9174506   1.12901845]

Eigenvectors of the Symmetric Matrix:
 [[ 0.62260932  0.77681612 -0.09441584]
 [ 0.41189996 -0.42791432 -0.80450467]
 [ 0.66535409 -0.46200222  0.58639397]]
